SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE inscrire;
TRUNCATE TABLE programme;
TRUNCATE TABLE module;
TRUNCATE TABLE session;
TRUNCATE TABLE user;
TRUNCATE TABLE stagiaire;
TRUNCATE TABLE formateur;
TRUNCATE TABLE categorie;

SET FOREIGN_KEY_CHECKS = 1;